version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16
  hugo: circleci/hugo@1.2.2

jobs:
  deploy:
    parameters:
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: "."
      - aws-s3/sync:
          from: "public"
          to: "s3://${AWS_S3_BLOG_DOMAIN}/"

workflows:
  main:
    jobs:
      - hugo/build:
          filters: &tagged
            branches:
              ignore: /.*/
            tags:
              # Semver patterns - will only build something new if you tag it correctly.
              only: /^\d+\.\d+\.\d+$/
          html-proofer: false
          source: "personal-blog"
          version: "0.87.0"
      - deploy:
          filters:
            <<: *tagged
          requires:
            - hugo/build
