version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16
  hugo: circleci/hugo@0.6.0

jobs:
  deploy:
    parameters:
      workspace-name:
        type: string
        description: "Workspace name with build artifacts."
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: "<< parameters.workspace-name >>"
      - aws-s3/sync:
          from: "./public"
          to: "s3://${AWS_S3_BLOG_DOMAIN}/"

workflows:
  main:
    jobs:
      - hugo/build:
          filters: &tagged
            branches:
              ignore: /.*/
            tags:
              # Semver patterns - will only build something new if you tag it correctly.
              only: /^\d+\.\d+\.\d+$/
          html-proofer: true
          source: "personal-blog"
          persist-to-workspace: true
      - deploy:
          filters:
            <<: *tagged
          requires:
            - hugo/build
          workspace-name: "public"
