# Generic config.

title = "Bartłomiej Szostek"
baseurl = "https://basz.co.uk/"
languageCode = "en-gb"
copyright = "Copyright &copy; 2020 - Bartłomiej Szostek"

paginate = 5
summaryLength = "30"
enableEmoji = "true"
uglyurls = "true"

# Theme configuration.

theme = "hugo-kiera"

pygmentsCodeFences = "true"

[author]
    name     = "Bartłomiej Szostek"
    github   = "bartelemi"
    linkedin = "bartlomiej-szostek"

[params]
    # favicon = ""
    tagline = "Personal blog for tech and thoughts."
    description = "Personal blog for tech and thoughts."

  [[menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags"
      weight = "1"
